### ISSUE TITLE
caller memorizer - watpliwosci co do tresci

### ISSUE THREAD

**Issue by vbaaccess** [daft-academy/daftacademy-python4beginners-autumn2021#10]
W przykładzie jest pokazane że używamy funkcji `shuffle` która jest z modułu `random`. 
Na końcu jest zastrzeżenie żeby nie korzystać z importów.

Jeśli dla uproszczenia będzie w tym przykładzie zaimportowana tylko ta funkcja z nie będzie chyba problemu i test później przejdzie; czy nic się nie stanie jeśli w teście też jest import modułu `random`.

**Comment by vbaaccess** [comment]
Przyszła pora na zadanie 7, niestety po przeczytaniu go kilka razy i mam wrażenie że nie jest do końca określone co obie funkcje mają robić (??)
Z podanego sposobu wykorzystania domyślam się że chodzi o to by funkcja `caller`  układała(sortowała) nam i je wywoływała je wszystkie.
Natomiast funkcja 'memorizer' nie jest chyba opisana ? w przykładzie mieszkanie robi 'random.shuffle' więc co ma robić 'memorizer' ? nie jest to dla mnie jednoznacznie jasne.

```python
# Uzupełnij funkcje `memorizer` i `caller`.
#
# Funkcja `memorizer` jako argument otrzyma listę funkcji.
#
# Funkcja `caller` jako argument otrzyma listę tych samych funkcji
# jak `memorize` w losowej kolejności. Zadaniem `caller` jest
# wywołanie ich w takiej kolejności w jakiej zostały przekazane
# do `memorizer`.
#
# Funkcje `memorizer` i `caller` zostaną wykorzystane w przybliżeniu
# w poniższy sposób:
#
# functions_list = [func1, func2, func3]
# memorizer(functions_list)
# shuffle(functions_list)
# caller(funcions_list)
#
# Po wykonaniu powyższych kroków funkcje z `functions_list`
# powinny zostać wywołane w kolejności func1, func2, func3
# przez funkcję `caller`
#
# * Nie używaj zmiennych globalnych
# * Nie korzystaj z importów
# * Rezultat wykonania funkcji `memorizer` i `caller`
#   nie jest wykorzystywany, najlepiej nie korzytać z
#   `return` w ich implementacji
```

**Comment by krwiozercza-szynszyla** [comment]
> W przykładzie jest pokazane że używamy funkcji shuffle która jest z modułu random. Na końcu jest zastrzeżenie żeby nie korzystać z importów.

Nigdzie nie jest powiedziane aby korzystać z funkcji `shuffle`. Przykład z wywołaniami ma tylko pomóc w zrozumieniu jak dwie funkcje, które mają być w tym zadaniu zaimplementowane, będą wykorzystywane przez kod testujący.

1. Memorizer dostaje listę funkcji
2. Kod testujący miesza funkcje w tej liście
3. Caller dostaje listę pomieszanych funkcji i ma je wywołać w takiej kolejności w jakiej otrzymał je memorizer

> Natomiast funkcja 'memorizer' nie jest chyba opisana ? w przykładzie mieszkanie robi 'random.shuffle' więc co ma robić 'memorizer' ? nie jest to dla mnie jednoznacznie jasne.

Funkcja memorizer ma robić to co konieczne żeby Twoja implementacja `caller` dała sobie radę z wywołąniem funkcji w odpowiedniej kolejności.

**Comment by vbaaccess** [comment]
Czy w funkcji `caller `moge wywołać/odwołać się do funkcji `memorizer` ?
a jeśli nie to rozumiem że mogę założyć że znam specyfikę funkcji `memorizer` i wiem jak jest w niej zrobione "oznaczenie" kolejności i mogę się do tego "oznaczenia" odwołać, jakoś tak ?

**Comment by krwiozercza-szynszyla** [comment]
> Czy w funkcji caller moge wywołać/odwołać się do funkcji memorizer ?

Nie zalecam ale dopuszczam

> rozumiem że mogę założyć że znam specyfikę funkcji memorizer

Funkcja `caller` może polegać na implementacji funkcji `memorizer`
