### ISSUE TITLE
Task 5

### ISSUE THREAD

**Issue by Oskar1399** [daft-academy/daftacademy-python4beginners-autumn2021#11]
```
def multi_adders(n):
    lista = [0]*n
    for a in range(0,len(lista)):
        def f(x):
            return x+a
        lista[a] = f 
    return lista
```

W task 5 wykonuje taki kod, niestety wtedy wszystkie funkcje w liście są takie jak ostatnia. Mógłbym poprosić o jakiś pomysł jak to naprawić?

**Comment by krwiozercza-szynszyla** [comment]
@Oskar1399 zacznijmy od naprawienia formatowania treści tego issue.

 https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks

**Comment by Oskar1399** [comment]
> @Oskar1399 zacznijmy od naprawienia formatowania treści tego issue.
> 
> https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks

**Comment by Oskar1399** [comment]
Teraz chyba git formatowanie?

**Comment by krwiozercza-szynszyla** [comment]
> wszystkie funkcje w liście są takie jak ostatnia

Nie są:
```
>>> def multi_adders(n):
...     lista = [0]*n
...     for a in range(0,len(lista)):
...         def f(x):
...             return x+a
...         lista[a] = f 
...     return lista
... 
>>> functions = multi_adders(4)
>>> functions
[<function multi_adders.<locals>.f at 0x7f166a9b1670>, <function multi_adders.<locals>.f at 0x7f166a9b1700>, <function multi_adders.<locals>.f at 0x7f166a9b1790>, <function multi_adders.<locals>.f at 0x7f166a9b1820>]
```

Twoja implementacja `multi_adders` zwraca n różnych funkcji (mają różne adresy) robiących przez przypadek to samo. Sprawdź jakie wartości `x` i `a` widzi każda z funkcji `f` (np. prostym `print`em), to powinno mniej więcej wskazać kierunek googlowania.
