### ISSUE TITLE
caller memorizer - brak pomysłu

### ISSUE THREAD

**Issue by Oskar1399** [daft-academy/daftacademy-python4beginners-autumn2021#12]
Wiem, że już trochę późno, ale od kilku godzin stoję w miejscu i nie mogę wymyślić nic do tego zadania. Może jakaś mała podpowiedź?
Próbowałem paru rzeczy, ale nie wiem jak zapisać kolejność tych funkcji w memorizer żeby móc je potem jakoś w caller wykorzystać. Czy może w ogóle nie w te stronę kombinuje?

**Comment by krwiozercza-szynszyla** [comment]
Wykład - 4.5 Funkcja jest obiektem

https://github.com/daft-academy/daftacademy-python4beginners-autumn2021/blob/main/2_Funkcjonalny_Kod/2.Funkcjonalny_Kod.ipynb
