### ISSUE TITLE
polynominal - wątpliwości do rzutowania na string

### ISSUE THREAD

**Issue by Kjablono** [daft-academy/daftacademy-python4beginners-autumn2021#13]
Mam dwie wątpliwości co do metody rzutującej na string i oczekiwanego rezultatu

1.  Według pierwszej '*' z instrukcji `Polynominal() -> 0`, wynika z tego że taki wielomian jest stały i ma wartość 0 (równoważny `Polynominal(0)`), natomiast w przykładzie rzutowania na `string` mamy `Polynominal() == '' `. Czy rzutowanie to ma zwracać pustego stringa dla wszystkich wielomianów stopnia 0 czy tylko dla tego konkretnego lub czy wkradł się tu jakiś błąd w przykładach?
2. Znaki `+/-` we wszystkich przykładach z instrukcji mają "dookoła" spację, poza ostatnim `str(Polynominal(-1)) == "-1"`, podobnie dzieje się w teście na codingrooms
```python
Traceback (most recent call last):
  File "/usercode/coding_rooms_unit_tests.py", line 30, in test_str_repr
    self.assertEqual(str(Polynominal(*coefficients)), str_repr)
AssertionError: '- 1 - x - x^3' != '-1 - x - x^3'
```
Czy można prosić o skontrolowanie, czy na pewno jest to spodziewane?

**Comment by krwiozercza-szynszyla** [comment]
1. -> "rzutowanie to ma zwracać pustego stringa dla wszystkich wielomianów stopnia 0"
2. Jeśli współczynnik jest pierwszym który pojawia się w stringu to ma nie być spacji np. `-1 + 2x` albo `-2x^2 + 3x^4`
