### ISSUE TITLE
Bee - wartosc zwracana z get_hive

### ISSUE THREAD

**Issue by StanislavRuduka** [daft-academy/daftacademy-python4beginners-autumn2021#14]
Nie moge skumac kolejnosci sprawdzania w testach, czy ja powinnem posortowac swoja odpowiedz, albo moze to nie powinna byc lista?

Moj kod:
```
class Bee():
    
    instances = []

    def __init__(self, name, identifier):
        self.name = name
        self.identifier = identifier
        

    def __str__(self):
        self.instances.append(f"{self.identifier} {self.name}")
        return f"{self.identifier} {self.name}"

    def get_hive(self):
        return self.instances
```

Error z testow: 
F
======================================================================
FAIL: test_default_case (coding_rooms_unit_tests.TestBee)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usercode/coding_rooms_unit_tests.py", line 25, in test_default_case
    self.assertEqual(bee.get_hive(), expected_hive)
AssertionError: ['222 Maja', '4234 Gucio', '1 Honey'] != {'4234 Gucio', '222 Maja', '1 Honey'}

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (failures=1)

**Comment by krwiozercza-szynszyla** [comment]
1. Formatuj rezultat testow tak jak formatujesz kod
2. Tresc zadania jasno wskazuje na typ kolekcji do zwrocenia z metody `get_hive`
```
# * Obiekty klasy `Bee` mają metodę `get_hive()` zwracającą zbiór tekstowych
#   reprezentacji wszyskich utworzonych instancji klasy Bee
```
