### ISSUE TITLE
StockQuantitySorter - o co chodzi z tą analogią

### ISSUE THREAD

**Issue by vbaaccess** [daft-academy/daftacademy-python4beginners-autumn2021#16]
Czy w zadaniu chodzi o napisanie dowolnej metody np.: `my_sort`?
Czy nienadpisanie to chodzi o to by wykonywało napisanie wersji `sort` która wykonuje bazową czynność i potem opisaną.
   Za bardzo nie rozumiem jak klasa ma być analogiczna ale bez nadpisania.

   Przydał by się też przykład jak to wstępnie przetestować.

**Comment by krwiozercza-szynszyla** [comment]
> Czy w zadaniu chodzi o napisanie dowolnej metody np.: my_sort?

Nie

> Czy nienadpisanie to chodzi o to by wykonywało napisanie wersji sort która wykonuje bazową czynność i potem opisaną.

Nie rozumiem tego zdania. Nie wolno w `StockQuantitySorter` zadeklarować metody `sort`.

> Przydał by się też przykład jak to wstępnie przetestować.

```python
item_a = StockItem("a", 100)
item_b = StockItem("b", 50)
item_c = StockItem("c", 110)

stock = [item_c, item_a, item_b]

stock_sorter = StockSorter()
stock_quantity_sorter = StockQuantitySorter()

stock_sorter.sort(stock) == [item_a, item_b, item_c]
stock_quantity_sorter.sort(stock) == [item_b, item_a, item_c]
```
