### ISSUE TITLE
Polynominal - niepoprawny test

### ISSUE THREAD

**Issue by Path-Finder-00** [daft-academy/daftacademy-python4beginners-autumn2021#17]
Z treści zadania wynika, że str(Polynominal()) powinno zwracać "0", ale test wymaga, by zwracało pustego stringa "".

**Comment by krwiozercza-szynszyla** [comment]
Z treści zadania wynika, że `str(Polynominal())` powinno zwracać `''` i test jest poprawny.

```
# * Instancje można rzutować na typ `string`, format podany w przykładach
#   str(Polynominal()) == ''
#   str(Polynominal(1, 2, 3)) == "1 + 2x + 2x^2"
#   str(Polynominal(0, 0, 5)) == "5x^2"
#   str(Polynominal(1, 1, 1, 1)) == "1 + x + x^2 + x^3"
#   str(Polynominal(0, 2, 0)) == "2x"
#   str(Polynominal(1, -1, 1, -1)) == "1 - x + x^2 - x^3"
#   str(Polynominal(-1)) == "-1"
```

**Comment by Path-Finder-00** [comment]
Faktycznie, przepraszam! Zmyliło mnie: 
* Instancjonowanie odbywa się poprzez podanie kolejnych
współczynników wielomianu np.
Polynominal()  ->  0

**Comment by vbaaccess** [comment]
o co chodzi w punkcie
```
# * Klasa `Polynominal` posiada metodę `from_iterable` umożliwiającą
#   instancjonowanie obiektów z wykorzystaniem iterowalnych kolekcji
#   współczynników
#   Polynominal.from_iterable([1, 2, 3]) == Polynominal(1, 2, 3)
#   Polynominal.from_iterable((1, 1, 5)) == Polynominal(1, 2, 3)
#
# * Współczynniki są liczbami całkowitymi
```
czy o to ze klasa ma mieć możliwość przyjmowania jako argumentu listy ?
czyli że zamiast deklarować wielomian `Polynominal(1, 2, 3)`
można to zrobić podają listę argumentów `Polynominal.from_iterable((1, 1, 5))`
(czyli jeden argument typ lista) a klasa sobie ma z tym poradzić

**Comment by krwiozercza-szynszyla** [comment]
@vbaaccess osobny issue
