### ISSUE TITLE
lazy_scribe - test nie przechodzi

### ISSUE THREAD

**Issue by YupiKayey** [daft-academy/daftacademy-python4beginners-autumn2021#2]
```
def lazy_scribe(sources: list):
    result: str = ''
    char_iterator = 0
    max_len = len(max(sources, key=len))
    while char_iterator < max_len:
        for source in sources:
            if char_iterator < len(source):
                result += source[char_iterator]
        char_iterator += 1
    string = result
    result = ''
    count = 1
    for i in range(len(string) - 1):
        if string[i] == string[i+1]:
            count = count + 1
        else:
            result = result + str(count) + string[i]
            count = 1
    result = result + string[-1]
    result = result.replace('1', '')
    return result


sources = ['python', 'java', 'golang']
print(lazy_scribe(sources))
```

Output: pjgyaotvlh2ao2ng
Sprawdzałem na innych przykładach i zawsze wychodzi ok, mimo to nie przechodzi testu. Mogę prosić o wskazanie co tu poprawić?

**Comment by krwiozercza-szynszyla** [comment]
@YupiKayey Przeanalizuj komunikat po uruchomieniu testów na CodingRooms. Będą tam wszystkie informacje potrzebne do poprawnienia tego rozwiązania.

**Comment by Oskar1399** [comment]
![image](https://user-images.githubusercontent.com/94389246/141819369-2498f517-3953-44e5-aac9-2df40c18f1b5.png)

Chciałbym się zapytać dlaczego nie mogę wziąć na tej platformie coding rooms elementu z listy results ani results1. Wykonuje cały kod w jupyterze i wszystko działa, a tutaj wygląda jakby te zmienne były pustymi stringami (a nie są, jak pominę tę linijkę to dostaję ładnego poszukiwanego przez nas stringa tylko, że bez ostatniej litery). Dodam, że jak spróbowałem wsadzić te dodawanie do pętli to również na jupyterze wszystko chodziło natomiast tutaj wyskakiwał błąd ale bez żadnego komentarza.

**Comment by Oskar1399** [comment]
![image](https://user-images.githubusercontent.com/94389246/141820147-940d93e1-4839-4171-a8bf-97782a5034ce.png)

**Comment by krwiozercza-szynszyla** [comment]
@Oskar1399 załóż osobny issue,  nie wklejaj screenów tylko przekopiuj treść komunikatu
