### ISSUE TITLE
subsets_everywhere - niepoprawny test

### ISSUE THREAD

**Issue by StanislavRuduka** [daft-academy/daftacademy-python4beginners-autumn2021#3]
Dostaje taki error przy input={1,2,3}:

![image](https://user-images.githubusercontent.com/70904620/141698200-f503e28d-8f7c-49b0-adc2-c6443f51300e.png)

Czy to czasem nie powinno byc:
{frozenset({1, 2}), frozenset({2, 3}), frozenset({1, 3})} - ?

**Comment by krwiozercza-szynszyla** [comment]
Treść zadania mówi: 
```
# Napisz program tworzący ze zbioru `elements` zbiór zawierający wszystkie
# podzbiory `elements` (włącznie z pustym i `elements`).
```
Zakładając, że elements jest zbiorem `{1, 2, 3}` w Twojej propozycji rozwiązania (`{{1,2}, {2,3}, {1,3}}`) brakuje `{}`, `{1, 2, 3}` ,`{1}` i kilku innych.

No i z tego co widze to aktualnie Twoja implementacja zwraca z funkcji `test_multiple_cases` wartość `None` to też trzeba jbc poprawić.

BTW. Nie wklejaj screenshota tylko text `Summary`
