### ISSUE TITLE
for_else, sum_until - kod działa lokalnie, wysypuje się na Coding Rooms

### ISSUE THREAD

**Issue by Sharrix** [daft-academy/daftacademy-python4beginners-autumn2021#4]
Proszę o pomoc. Kod działa w Visual Code Studio, a Coding Rooms wywala błędy(screeny załączone)
```
def for_else(values: list):
    # Uzupełnij poniższą pętlę `for` tak, aby zmienna `result` przyjmowała wartość `False`
    # jeśli w liście `values` nie ma wartości 10
    result: bool = True

    for value in values:
        result = 10 in values
    else:
        print(result)
    return result
```
```
def sum_until(values: list, stop_value: int):
    # Uzupełnij poniższą pętlę tak, zmienna `result` przyjmowała wartość sumy elementów znajdujących
    # się w liście `values` przed pierwszym wystąpieniem wartości `stop_value`
    # Przykład:
    # Dla `values = [1, 1, 3]` i `stop_value = 3` zmienna `result` powinna przyjąć wartość `2`
    result: int = 0

    for value in values:
        if value < stop_value:
            result += value
    return result
```
![blad_1](https://user-images.githubusercontent.com/62251687/141815669-697db9fc-c677-4d5b-9f6e-bf070f28b0b7.png)
![blad_2](https://user-images.githubusercontent.com/62251687/141815675-16338d4b-f358-4460-a428-50d39e3ba0c7.png)

**Comment by krwiozercza-szynszyla** [comment]
`sum_until` - Twoje rozwiązanie sumuje elementy mniejsze niż `stop_value`, to co innego niż suma elementów listy przed pierwszym wsytąpieniem `stop_value`

Twoje rozwiązanie dla przypadku `values = [1, 1, 10, 1, 1], stop_value=10` przyjmie wartość `4` co odpowiada sumie elementów mniejszych niż 10

Poprawne rozwiązanie powinno w tym przypadku zwrócić 2 - jest to suma elementów występujących w liście przed pierwszym wystąpieniem `stop_value`

**Comment by krwiozercza-szynszyla** [comment]
`for_else` - w załączonym screenie masz napisane dla jakiego przykładu testowego to rozwiązanie nie działa, przy pustej tablicy ciało pętli iterującej po niej sie nie wykona

**Comment by krwiozercza-szynszyla** [comment]
> Kod działa w Visual Code Studio, a Coding Rooms wywala błędy

Kod działa i tu i tu, błedy w Coding Rooms wskazują jedynie na to, że nie robi tego co powinien ;P
