### ISSUE TITLE
lazy_scribe - index out of range

### ISSUE THREAD

**Issue by Oskar1399** [daft-academy/daftacademy-python4beginners-autumn2021#5]
```
ERROR: test_multiple_cases (coding_rooms_unit_tests.TestLazyScribe) (input=[''])
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usercode/coding_rooms_unit_tests.py", line 19, in test_multiple_cases
    result = lazy_scribe(input)
  File "/usercode/task6.py", line 65, in lazy_scribe
    result += result1[-1]
IndexError: string index out of range
```

Chciałbym się zapytać dlaczego nie mogę wziąć na tej platformie coding rooms elementu z listy results ani results1. Wykonuje cały kod w jupyterze i wszystko działa, a tutaj wygląda jakby te zmienne były pustymi stringami (a nie są, jak pominę tę linijkę to dostaję ładnego poszukiwanego przez nas stringa tylko, że bez ostatniej litery). Dodam, że jak spróbowałem wsadzić te dodawanie do pętli to również na jupyterze wszystko chodziło natomiast tutaj wyskakiwał błąd ale bez żadnego komentarza.

**Comment by krwiozercza-szynszyla** [comment]
Fragmenty kodu i output z testów wrzucamy z pomocą `insert code` w narzędziach. Zedytowałem treść issue żebyś zobaczył jak powinno to wyglądać

**Comment by Oskar1399** [comment]
`    result: str = ''
    result1 = ''
    max_len = 0
    for słowo in sources:
        if len(słowo) > max_len:
            max_len = len(słowo)
    
    i = 0
    while i <= max_len:
        for słowo in sources:
            if i >= len(słowo):
                continue
            result1 = result1 + słowo[i]
        i += 1
    
    
    
    powt = 1

    for i in range(len(result1)-1):
        if result1[i]==result1[i+1]:
            powt += 1
        else:
            if powt > 1:
                result = result + str(powt) + result1[i]
            else:
                result = result + result1[i]
            powt = 1

    result += result1[-1]  
    
    return result`

**Comment by krwiozercza-szynszyla** [comment]
Nie ma możliwości żeby Jupyter działał inaczej w tym przypadku niż Coding Rooms. Jedyną możliwością jest to, że nie uruchamiasz kodu napisanego w Jupyterze dla przypadku testowanego w Coding Rooms. Jaki to jest przypadek możesz wyczytać z treści komunikatu.

> nie mogę wziąć na tej platformie coding rooms elementu z listy results ani results1

`IndexError: string index out of range` wskazuje na to, że `results1` nie jest listą a stringiem
