### ISSUE TITLE
calculator - brak pomysłu patrząc na wykład

### ISSUE THREAD

**Issue by vbaaccess** [daft-academy/daftacademy-python4beginners-autumn2021#8]
Nie jestem pewien czy to poprawny kierunek na rozwiązanie zadanie
```python
def calculator(arg=None) -> int:
    result = 0
    if arg!=None:
        if arg=="=":
             return result
        else:
            print(arg)
            return calculator
    return result
```
udaje mi się wypisać przekazane argumenty, ale w nie mam pomysłu jak przy rekurencji przekazać parametr
oczywiście przy założeniu nie wykorzystywania zmiennych globalnych oraz importowania modułów

**Comment by krwiozercza-szynszyla** [comment]
Potestuj co funkcja zadeklarowana wewnątrz innej funkcji może zdziałać korzystając ze zmiennych zadeklarowanych w fukcji zewnętrznej

**Comment by vbaaccess** [comment]
czy funkcja 
```python
local
```
jest dozwolona ?

update:
tak chodziło o
```python
nonlocal
```

**Comment by krwiozercza-szynszyla** [comment]
Co to "funkcja `local`"?

Jeśli chodzi o wykorzystanie keyword'a `nonlocal` to można, ale da się to zadanie rozwiązać bez tej techniki (bo chyba nie bylo jej na wykładzie).

**Comment by Sharrix** [comment]
proszę o podpowiedź jak loopować po kolejnych funkcjach/parametrach?

**Comment by krwiozercza-szynszyla** [comment]
@Sharrix To co pisałem:
> Potestuj co funkcja zadeklarowana wewnątrz innej funkcji może zdziałać korzystając ze zmiennych zadeklarowanych w fukcji zewnętrznej

Dokładniej mówie o takiej sytuacji:
```python
def outer():
    outer_var = ...
    def inner():
        ...
```

Potestuj co funkcja `inner` może zdziałać wykorzystując zmienna `outer_var` zadeklarowaną w funkcji zewnętrznej. Pamiętaj, że `outer_var` nie musi być typem podstawowym.
